# Generated by Django 5.1.3 on 2025-05-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartv2', '0002_add_product_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
